# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20161001_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='youtube_id',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
