# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 01:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0003_event_youtube_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='host',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='host', to=settings.AUTH_USER_MODEL),
        ),
    ]
